Repository dnd-mentee-4th/dnd-mentee-4th-1-frontend, pull requests merged in 2021-02, with the labels that each got.

#48 Feature/#41 search fragment
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/data/datasource/local/LocalDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchFragment.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchViewHolder.kt
  app/src/main/java/com/example/myapplication/result/ResultFragement.kt
  app/src/main/res/anim/enter_from_left.xml
  app/src/main/res/anim/enter_from_right.xml
  app/src/main/res/anim/exit_to_left.xml
  app/src/main/res/anim/exit_to_right.xml
  app/src/main/res/drawable-v24/select_border_layout.xml
  app/src/main/res/drawable/button_search.xml
  app/src/main/res/drawable/item_result_recipe.xml
  app/src/main/res/drawable/spinner_default_background.xml
  app/src/main/res/layout/custom_auto_complete_item_line.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_random_recipe.xml
  app/src/main/res/layout/item_result_recipe.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/transition/shared_image.xml
  app/src/main/res/values/styles.xml
Labels: 검색

#54 Feature/#45 detail fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/detail/DetailStepsAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailViewPagerStepsAdapter.kt
  app/src/main/java/com/example/myapplication/detail/ExpandableCountryModel.kt
  app/src/main/java/com/example/myapplication/navigation/Login/LoginActivity.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteActivity.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchFragment.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity2.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity3.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity4.kt
  app/src/main/java/com/example/myapplication/result/ResultAdapter.kt
  app/src/main/java/com/example/myapplication/result/ResultFragement.kt
  app/src/main/res/drawable/detail_tag_button.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/item_result_recipe.xml
  app/src/main/res/drawable/ratingbar_background.xml
  app/src/main/res/drawable/round_left_button.xml
  app/src/main/res/drawable/round_right_button.xml
  app/src/main/res/drawable/round_spinner.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialogue_star_rating.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_step_description_slide.xml
  app/src/main/res/layout/item_random_recipe.xml
  app/src/main/res/layout/item_result_recipe.xml
  app/src/main/res/layout/list_header.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_yorijori.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_yorijori.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_yorijori.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_yorijori.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_yorijori.png
  app/src/main/res/values/styles.xml
Labels: 검색, 상세레시피

#56 Feature/#45 detail fragment
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailCommentViewHolder.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/detail/DetailStepsAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailTagAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailTagViewHolder.kt
  app/src/main/java/com/example/myapplication/detail/DetailViewPagerPicsAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchFragment.kt
  app/src/main/java/com/example/myapplication/result/ResultFragement.kt
  app/src/main/res/drawable/cursor_color.xml
  app/src/main/res/drawable/tag_button.xml
  app/src/main/res/layout/dialogue_star_rating.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_image_slide.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_result_recipe.xml
  app/src/main/res/layout/tag_button_item.xml
Labels: 검색, 상세레시피

#60 Feature #55 레시피 등록
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/navigation/home/MultiViewAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteActivity.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteCommentAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteFilterAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity2.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity3.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity4.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadCommentAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadFilterAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadPreviewFilterAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadRecipeAdapter.kt
  app/src/main/res/drawable/ic_cancel_upload.png
  app/src/main/res/drawable/ic_cancel_upload.xml
  app/src/main/res/drawable/ic_oval.xml
  app/src/main/res/drawable/no_select_border_layout.xml
  app/src/main/res/layout/activity_quote.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/activity_upload2.xml
  app/src/main/res/layout/activity_upload3.xml
  app/src/main/res/layout/activity_upload4.xml
  app/src/main/res/layout/filter_list_item.xml
  app/src/main/res/layout/quote_comment_list_item.xml
  app/src/main/res/layout/upload_preview_recipe_list_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: P1, 레시피등록

#68 Feature/#61 login activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/myapplication/MainActivity.kt
  app/src/main/java/com/example/myapplication/SharedPreferenceUtil.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/navigation/Login/LoginActivity.kt
  app/src/main/java/com/example/myapplication/navigation/mypage/SettingActivity.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteActivity.kt
  app/src/main/java/com/example/myapplication/navigation/quote/QuoteFilterAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity2.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity3.kt
  app/src/main/java/com/example/myapplication/navigation/upload/UploadActivity4.kt
  app/src/main/res/drawable/dialog_nickname_background.xml
  app/src/main/res/drawable/ic_cook.png
  app/src/main/res/drawable/top_border.xml
  app/src/main/res/layout/activity_quote.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/activity_upload2.xml
  app/src/main/res/layout/activity_upload3.xml
  app/src/main/res/layout/activity_upload4.xml
  app/src/main/res/layout/dialog_nickname.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: P3, 로그인, 인용하기

#69 Feature/#62 result fragment
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailCommentAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailCommentViewHolder.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/detail/DetailMainIngredientAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailStepsAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailSubIngredientAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailTagAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailTagViewHolder.kt
  app/src/main/java/com/example/myapplication/detail/DetailViewPagerPicsAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchAdapter.kt
  app/src/main/java/com/example/myapplication/navigation/search/SearchFragment.kt
  app/src/main/java/com/example/myapplication/result/ResultAdapter.kt
  app/src/main/java/com/example/myapplication/result/ResultFragement.kt
  app/src/main/java/com/example/myapplication/result/ResultMainIngredientAdapter.kt
  app/src/main/java/com/example/myapplication/result/ResultViewHolder.kt
  app/src/main/res/drawable-v24/calendar.png
  app/src/main/res/drawable-v24/delete_icon.png
  app/src/main/res/drawable-v24/empty_search_item.png
  app/src/main/res/drawable-v24/like_clicked.png
  app/src/main/res/drawable-v24/like_default.png
  app/src/main/res/drawable-v24/rating_star_clicked.png
  app/src/main/res/drawable-v24/rating_star_default.png
  app/src/main/res/drawable-v24/search_illustration.png
  app/src/main/res/drawable-v24/watch.png
  app/src/main/res/drawable/background_ingredient.xml
  app/src/main/res/drawable/circle_imageview.xml
  app/src/main/res/drawable/tag_button.xml
  app/src/main/res/layout/dialogue_star_rating.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_main_ingredient.xml
  app/src/main/res/layout/item_result_main_ingredient.xml
  app/src/main/res/layout/item_result_recipe.xml
  app/src/main/res/layout/list_comment_of_recipe.xml
  app/src/main/res/layout/no_result_background.xml
  app/src/main/res/layout/spinner_item.xml
  app/src/main/res/layout/tag_button_item.xml
  app/src/main/res/values/styles.xml
Labels: 검색, 결과, 상세레시피

#81 [Update] 레이아웃 수정
  .idea/codeStyles/Project.xml
  app/src/main/java/com/example/myapplication/data/datasource/remote/RemoteDataSource.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeApi.kt
  app/src/main/java/com/example/myapplication/data/datasource/remote/api/RecipeDTO.kt
  app/src/main/java/com/example/myapplication/data/repository/Repository.kt
  app/src/main/java/com/example/myapplication/detail/DetailCommentAdapter.kt
  app/src/main/java/com/example/myapplication/detail/DetailFragment.kt
  app/src/main/java/com/example/myapplication/detail/DetailTagViewHolder.kt
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/item_result_recipe.xml
Labels: 검색
